name: Eclipse
options:
  deploymentTarget:
    iOS: "15.0"

packages:
  Tun2SocksKit:
    url: https://github.com/EbrahimTahernejad/Tun2SocksKit
    branch: main

targets:
  Eclipse:
    type: application
    platform: iOS
    sources: [App, Shared]
    dependencies:
      - target: EclipseTunnel
    info:
      path: App/Info.plist
      properties:
        UILaunchScreen: {}
        CFBundleDisplayName: Eclipse
        CFBundleShortVersionString: "1.3"
        CFBundleVersion: "4"
        NSCameraUsageDescription: Камера нужна для сканирования QR-кода подписки
    entitlements:
      path: App/App.entitlements
      properties:
        com.apple.developer.networking.networkextension:
          - packet-tunnel-provider
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.vpntest
        PRODUCT_NAME: Eclipse
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_VERSION: "5.0"

  EclipseTunnel:
    type: app-extension
    platform: iOS
    sources: [Tunnel, Shared]
    dependencies:
      - framework: Frameworks/Xray.xcframework
        embed: false
        link: true
      - package: Tun2SocksKit
      - sdk: libresolv.tbd
    info:
      path: Tunnel/Info.plist
      properties:
        CFBundleDisplayName: Eclipse Tunnel
        CFBundleShortVersionString: "1.3"
        CFBundleVersion: "4"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.networkextension.packet-tunnel
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).PacketTunnelProvider
    entitlements:
      path: Tunnel/Tunnel.entitlements
      properties:
        com.apple.developer.networking.networkextension:
          - packet-tunnel-provider
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.vpntest.tunnel
        PRODUCT_NAME: EclipseTunnel
        SWIFT_VERSION: "5.0"
